name: Main

on:
  push:
    branches:
      - main

env:
  ACTION_NAME: github-semver-parse

jobs:
  pre-commit:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v3
      - uses: pre-commit/action@v3.0.0

  unit-tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Setup Node.js environment
        uses: actions/setup-node@v3
        with:
          node-version: "16"
      - name: Install dependencies
        run: npm install
      - name: Test
        run: npm test

  integration-tests:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Run action
        uses: ./
        id: yamler
        with:
          yaml-file: "__tests__/test.yaml"

      # Use the output from the yamler step
      - name: Output Test
        run: |
          echo "${{ steps.yamler.outputs.yaml }}"
          echo "${{ steps.yamler.outputs.what_it_is }}"
          echo "${{ steps.yamler.outputs.yaml_resources__yaml_1_2_3rd_edition }}"

  release-pull-request:
    runs-on: ubuntu-latest
    needs: [pre-commit, unit-tests, integration-tests]
    steps:
      - uses: google-github-actions/release-please-action@v3
        id: release
        with:
          release-type: simple
          command: release-pr
          package-name: ${{ env.ACTION_NAME }}
          bump-minor-pre-major: true
