name: Main

on:
  push:
    branches:
      - main

env:
  ACTION_NAME: yamler

jobs:
  pre-commit:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: "3.10"
      - uses: pre-commit/action@v3.0.0

  unit-tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Setup Node.js environment
        uses: actions/setup-node@v3
        with:
          node-version: "16"
      - name: Install dependencies
        run: npm install
      - name: Test
        run: npm test

  integration-tests:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Run action
        uses: ./
        id: yamler
        with:
          yaml-file: "__tests__/test.yaml"

      - name: Check steps.yamler.outputs.yaml output value
        run: |
          [[ "${{ steps.yamler.outputs.yaml }}" == "YAML Ain't Markup Language" ]]

      - name: Check steps.yamler.outputs.what_it_is output value
        run: |
          [[ "${{ steps.yamler.outputs.what_it_is }}" == "YAML is a human friendly data serialization standard for all programming languages." ]]

      - name: Check steps.yamler.outputs.yaml_resources__yaml_1_2_3rd_edition output value
        run: |
          [[ "${{ steps.yamler.outputs.yaml_resources__yaml_1_2_3rd_edition }}" == "http://yaml.org/spec/1.2/spec.html" ]]

  release-please:
    runs-on: ubuntu-latest
    needs: [pre-commit, unit-tests, integration-tests]
    permissions:
      contents: write
      pull-requests: write
    steps:
      - uses: google-github-actions/release-please-action@v3
        id: release
        with:
          release-type: simple
          command: release-pr
          package-name: ${{ env.ACTION_NAME }}
          bump-minor-pre-major: true
